### ISSUE TITLE
7-11集的呢？弃坑了？

### ISSUE THREAD

**Issue by DUNRAVEN-FOUNDATION** [UESTC-Ingress/Ingress_animation_sub#1]
哪里能找到字幕啊。。。

**Comment by YukariChiba** [comment]
本字幕是不完全不专业的紧急翻译，早已弃坑，建议前往国内各大知名字幕站点搜寻，或下载内嵌字幕的版本。
另：DUNRAVEN-FOUNDATION计划包含了字幕的相关情报，若有需要可在你司内部数据库中查找。
